### ISSUE TITLE
DroughtStress group missing soil depth data and bin ID's

### ISSUE THREAD

**Issue by ncemery** [ncemery/4460_LastheniaDispersal#10]
Cat - we are missing the following data from your team's experiment:
1) the height of the soil below the edge of each pot
2) the original bin that each pot was in
Can you see if you can dig up this info?

**Comment by ncemery** [comment]
Kate - we are missing the following from the Variability group's experiment:
1) the height of the soil below the edge of each pot
2) the original bin location of each pot
Do you have that information? If so, can you send it to me or add it into the spreadsheet yourself through Github?

**Comment by ncemery** [comment]
@Catarcher - can you please comment with an update on this issue? I can't recall where we left it.

**Comment by Catarcher** [comment]
@ncemery I just found the data regarding the original bin that each pot was in, and will be able to load that information in today. The height of the soil was already documented in the spreadsheet.

**Comment by Catarcher** [comment]
Data has been entered, bins are indicated as 1,2,3; originally the treatment was in this section (A,B,C) and I moved that to the correct column

**Comment by ncemery** [comment]
Thanks, Cat! I went ahead and merged this with the master document.
