### ISSUE TITLE
Missing data from Variability group

### ISSUE THREAD

**Issue by ncemery** [ncemery/4460_LastheniaDispersal#11]
Kate - we are missing the following from the Variability group's experiment:
1) the height of the soil below the edge of each pot
2) the original bin location of each pot
Do you have that information? If so, can you send it to me or add it into the spreadsheet yourself through Github?

**Comment by casc5962** [comment]
Nancy- I'm pretty sure we measured the soil after it has settled and recorded the location of our bins. Julie is storing all the physical copies of the data in her office, and I'm trying to get in touch with her to pick them up.

**Comment by ncemery** [comment]
Kate added the depth data while we were meeting in lab - will add bin ID's later

**Comment by ncemery** [comment]
Kate added the bin locations for each plant and Nancy updated the master file.
